// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRvkHFEv51j1vho9B3RO8UC8MD_djozUQ',
    appId: '1:806405631213:web:a1432c144ab5ceac7070e4',
    messagingSenderId: '806405631213',
    projectId: 'workout-tracker-bc51e',
    authDomain: 'workout-tracker-bc51e.firebaseapp.com',
    storageBucket: 'workout-tracker-bc51e.appspot.com',
    measurementId: 'G-G087XB57S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMctFqRDKhnH0buW6xmWxq7JGbcAkzw5s',
    appId: '1:806405631213:android:a65bf007ee1a028f7070e4',
    messagingSenderId: '806405631213',
    projectId: 'workout-tracker-bc51e',
    storageBucket: 'workout-tracker-bc51e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAQA5RhwUEk-tenz_43bd6Ng4aMKgrlww',
    appId: '1:806405631213:ios:6f76eb9f6fcd72147070e4',
    messagingSenderId: '806405631213',
    projectId: 'workout-tracker-bc51e',
    storageBucket: 'workout-tracker-bc51e.appspot.com',
    iosBundleId: 'com.example.flutterWorkoutTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAQA5RhwUEk-tenz_43bd6Ng4aMKgrlww',
    appId: '1:806405631213:ios:b94f1eef3aee9a137070e4',
    messagingSenderId: '806405631213',
    projectId: 'workout-tracker-bc51e',
    storageBucket: 'workout-tracker-bc51e.appspot.com',
    iosBundleId: 'com.example.flutterWorkoutTracker.RunnerTests',
  );
}
